version: "3.9"
services:

    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8088:80"
        volumes:
            - .:/app
        depends_on:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_CHARSET: ${DB_CHARSET}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USERNAME: ${MAILER_USERNAME}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: ${MAILER_ENCRYPTION}
            MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
            JWT_ENCRYPTION_KEY: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - .:/app
        secrets:
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
        networks:
            - app-network

    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_CHARSET: ${DB_CHARSET}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USERNAME: ${MAILER_USERNAME}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: ${MAILER_ENCRYPTION}
            MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
            JWT_ENCRYPTION_KEY: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - .:/app
        secrets:
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
        networks:
            - app-network

#    db:
#        image: mariadb
#        environment:
#            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
#            MARIADB_DATABASE: app
#        volumes:
#            - app-mariadb:/var/lib/mysql/data
#        networks:
#            - app-network

#    phpmyadmin:
#        image: phpmyadmin
#        environment:
#            - PMA_ARBITRARY=1
#            - UPLOAD_LIMIT=500M
#        ports:
#            - "8888:80"
#        networks:
#            - app-network
#
#    mailer:
#        image: mailhog/mailhog
#        ports:
#            - "8889:8025"
#        networks:
#            - app-network

volumes:
    app-mariadb:

networks:
    app-network:
        driver: bridge

secrets:
    jwt_encryption_key:
        file: ./docker/development/secrets/jwt_encryption_key
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public_key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private_key
